### PR TITLE
fix(engines): less restrictive node version

### PR DESCRIPTION
**Pull request by drwpwrs**
Change `package.json` `engines.node` to allow for any version of node 18 at or above `18.12.1` per #191

### CODE REVIEW

**Review by saiichihashimoto — CHANGES_REQUESTED** [review]
Change the commit message to something like `fix(engines): less restrictive node versions`, something like that. `semantic-release` will make sure it ends up in the next deployment.

**Review by saiichihashimoto — APPROVED** [review]

**Comment by magicspon** [comment]
Any idea when this will be released.  Currently having some build issues on vercel due to node version.

**Review by saiichihashimoto — APPROVED** [review]

**Comment by saiichihashimoto** [comment]
Why aren't these status checks running?

**Comment by saiichihashimoto** [comment]
@drwpwrs idk why your status checks aren't kicking off, but I figured I'd unblock everyone by just recreating this. Sorry your change didn't go in 😢 #202

**Pull request closed without merging**
